In [3]:
import pandas as pd

In [ ]:
# df =pd.read_csv("../data/real_data_excel/production_data/COOIS_Planned_and_Released_251110.csv")
# df.to_csv("../data/raw_csv/COOIS_Planned_and_Released_251110.csv", index=False)

In [7]:
df2 = pd.read_csv("../data/raw_csv/demand_updates/COOIS_Planned_and_Released_260115.csv")
df2

,Order,Material Number,Material description,Order quantity (GMEIN),Basic start date,Basic finish date,GOS Text display for CPH production orde
0,100035977,S9999592,"2/3PP Syria Paediatric Kit,2019 S9935090",487,5/1/2026,9/1/2026,REL PRT PRC BCRQ MANC SETC
1,100036133,S9999883,Subkit 3/6 Obstetric 3-renew.S9908302,100,5/1/2026,9/1/2026,REL PRC BCRQ MANC SETC
2,100036571,S9998505,"Sub 4/7 SD IMCI Med. kit, 2016",64,5/1/2026,9/1/2026,REL PRC BCRQ MANC SETC
3,100036650,S9992476,"SUB 7/10 NBK, Hospital,Module 2,Consum",3,5/1/2026,9/1/2026,REL DLV PRC BCRQ MANC SETC
4,100036712,S9992587,"SUB 12/12 NBK, Hospital, Module 3, Equ",3,5/1/2026,9/1/2026,REL DLV PRC MANC SETC
...,...,...,...,...,...,...,...
335,100036563,S9999494,"Prepack 1/3 SD,Primary Healthcare2016",229,2/3/2026,6/3/2026,NaN
336,100036910,S9902480,"NBK, Hospital, Module 3, Equipment",3,2/3/2026,6/3/2026,NaN
337,100037188,S9991145,"SUB 1/5 IEHK 2024,Suppl. Medicine Inj.",200,2/3/2026,6/3/2026,NaN
338,100037191,S9991147,"SUB 3/5 IEHK 2024,Suppl. Medicine Inj.",200,2/3/2026,13/03/2026,NaN
339,100037204,S9906805,"Yemen PHC kit 2025, Supp. Medicines",220,2/3/2026,6/3/2026,NaN

In [9]:

df2 = pd.read_csv("../data/raw_csv/demand_updates/COOIS_Planned_and_Released_260115.csv")
df2['Basic start date'] = pd.to_datetime(df2['Basic start date'], dayfirst=True)
df2['Basic end date'] = pd.to_datetime(df2['Basic finish date'], dayfirst=True)

df2['Basic start date'] = df2['Basic start date'].dt.strftime('%Y-%m-%d')
df2['Basic end date'] = df2['Basic end date'].dt.strftime('%Y-%m-%d')
df2

,Order,Material Number,Material description,Order quantity (GMEIN),Basic start date,Basic finish date,GOS Text display for CPH production orde,Basic end date
0,100035977,S9999592,"2/3PP Syria Paediatric Kit,2019 S9935090",487,2026-01-05,9/1/2026,REL PRT PRC BCRQ MANC SETC,2026-01-09
1,100036133,S9999883,Subkit 3/6 Obstetric 3-renew.S9908302,100,2026-01-05,9/1/2026,REL PRC BCRQ MANC SETC,2026-01-09
2,100036571,S9998505,"Sub 4/7 SD IMCI Med. kit, 2016",64,2026-01-05,9/1/2026,REL PRC BCRQ MANC SETC,2026-01-09
3,100036650,S9992476,"SUB 7/10 NBK, Hospital,Module 2,Consum",3,2026-01-05,9/1/2026,REL DLV PRC BCRQ MANC SETC,2026-01-09
4,100036712,S9992587,"SUB 12/12 NBK, Hospital, Module 3, Equ",3,2026-01-05,9/1/2026,REL DLV PRC MANC SETC,2026-01-09
...,...,...,...,...,...,...,...,...
335,100036563,S9999494,"Prepack 1/3 SD,Primary Healthcare2016",229,2026-03-02,6/3/2026,NaN,2026-03-06
336,100036910,S9902480,"NBK, Hospital, Module 3, Equipment",3,2026-03-02,6/3/2026,NaN,2026-03-06
337,100037188,S9991145,"SUB 1/5 IEHK 2024,Suppl. Medicine Inj.",200,2026-03-02,6/3/2026,NaN,2026-03-06
338,100037191,S9991147,"SUB 3/5 IEHK 2024,Suppl. Medicine Inj.",200,2026-03-02,13/03/2026,NaN,2026-03-13
339,100037204,S9906805,"Yemen PHC kit 2025, Supp. Medicines",220,2026-03-02,6/3/2026,NaN,2026-03-06

In [ ]:
df2['Order quantity (GMEIN)'] = df2['Order quantity (GMEIN)'].str.replace(',', '')
df2['Order quantity (GMEIN)'] = df2['Order quantity (GMEIN)'].astype(int)
df2.to_csv("../data/raw_csv/demand_updates/COOIS_Planned_and_Released_260115.csv", index=False)

AttributeError: Can only use .str accessor with string values!

In [13]:
df2

,Order,Material Number,Material description,Order quantity (GMEIN),Basic start date,Basic finish date,GOS Text display for CPH production orde,Basic end date
0,100035977,S9999592,"2/3PP Syria Paediatric Kit,2019 S9935090",487,2026-01-05,9/1/2026,REL PRT PRC BCRQ MANC SETC,2026-01-09
1,100036133,S9999883,Subkit 3/6 Obstetric 3-renew.S9908302,100,2026-01-05,9/1/2026,REL PRC BCRQ MANC SETC,2026-01-09
2,100036571,S9998505,"Sub 4/7 SD IMCI Med. kit, 2016",64,2026-01-05,9/1/2026,REL PRC BCRQ MANC SETC,2026-01-09
3,100036650,S9992476,"SUB 7/10 NBK, Hospital,Module 2,Consum",3,2026-01-05,9/1/2026,REL DLV PRC BCRQ MANC SETC,2026-01-09
4,100036712,S9992587,"SUB 12/12 NBK, Hospital, Module 3, Equ",3,2026-01-05,9/1/2026,REL DLV PRC MANC SETC,2026-01-09
...,...,...,...,...,...,...,...,...
335,100036563,S9999494,"Prepack 1/3 SD,Primary Healthcare2016",229,2026-03-02,6/3/2026,NaN,2026-03-06
336,100036910,S9902480,"NBK, Hospital, Module 3, Equipment",3,2026-03-02,6/3/2026,NaN,2026-03-06
337,100037188,S9991145,"SUB 1/5 IEHK 2024,Suppl. Medicine Inj.",200,2026-03-02,6/3/2026,NaN,2026-03-06
338,100037191,S9991147,"SUB 3/5 IEHK 2024,Suppl. Medicine Inj.",200,2026-03-02,13/03/2026,NaN,2026-03-13
339,100037204,S9906805,"Yemen PHC kit 2025, Supp. Medicines",220,2026-03-02,6/3/2026,NaN,2026-03-06

In [2]:
df3=pd.concat([df, df2])
df3.head()
df3['Order quantity (GMEIN)'] = df3['Order quantity (GMEIN)'].str.replace(',', '')
df3['Order quantity (GMEIN)'] = df3['Order quantity (GMEIN)'].astype(int)
df3

NameError: name 'pd' is not defined

In [14]:
import pandas as pd
# df3['Basic start date'] = pd.to_datetime(df3['Basic start date'])
# df3['Basic end date'] = pd.to_datetime(df3['Basic end date'])
# df3['Basic start date'] = df3['Basic start date'].dt.strftime('%Y-%m-%d')
# df3['Basic end date'] = df3['Basic end date'].dt.strftime('%Y-%m-%d')
df2.to_csv("../data/real_data_excel/production_data/COOIS_Planned_and_Released_260115.csv", index=False)

In [ ]:
df2.to_csv("../data/real_data_excel/production_data/COOIS_Planned_and_Released_260115.csv", index=False)

In [15]:
df2.to_csv("../data/raw_csv/demand_updates/COOIS_Planned_and_Released_260115.csv", index=False)